Aliquot prop
autoprotocol/ascs pull request #28
Opened 2020-07-31 20:03 UTC by aota001

* Adds `compounds` as an aliquot properties

2020-07-31 21:09 UTC, joshhacksthings requested changes
Looks like a good first draft. I think we should clarify some phrasing, made comments about it.

2020-07-31 21:09 UTC, joshhacksthings commented on Proposed/asc054.md
> +Add `compounds` to aliquot property
syntactical nit:
Aliquots already have a top level attribute called `properties`, which is a dictionary. However I think what we're proposing here is to "Add `compounds` attribute to aliquot."

2020-07-31 21:09 UTC, joshhacksthings commented on Proposed/asc054.md
> +Well or aliquot often holds single of multiple compounds inside, but the data is not captured as an aliquot property
nit: spelling/phrasing? "often holds single or multiple"

2020-07-31 21:09 UTC, joshhacksthings commented on Proposed/asc054.md
> +in Python. Some of the compounds data we are proposing to include here are compound id, SMILES (Simplified Molecular-
The root cause here isn't that the compound info is not captured as an aliquot property - it can be, if specified in a protocol. It seems that the problem here is we want a top-level attribute which maps to a dictionary of information on a compound.

2020-07-31 21:09 UTC, joshhacksthings commented on Proposed/asc054.md
> +    "well_index": {
`"well_index"` here seems to contain the `compounds` dict?

2020-07-31 21:09 UTC, joshhacksthings commented on Proposed/asc054.md
> +Any `compounds` data attached to the specified aliquot will be transferred over as an aliquot
how? and will it? It looks like this `compounds` attribute is separate from properties

2020-07-31 21:12 UTC, aota001 commented on Proposed/asc054.md
> +Add `compounds` to aliquot property
Ah. Yes, that is correct.

2020-07-31 21:13 UTC, aota001 commented on Proposed/asc054.md
> +Well or aliquot often holds single of multiple compounds inside, but the data is not captured as an aliquot property
:p yes, typo...

2020-07-31 21:14 UTC, aota001 commented on Proposed/asc054.md
> +in Python. Some of the compounds data we are proposing to include here are compound id, SMILES (Simplified Molecular-
True... I will clarify that. Thanks!

2020-07-31 21:16 UTC, aota001 commented on Proposed/asc054.md
> +Any `compounds` data attached to the specified aliquot will be transferred over as an aliquot
ah. sorry for the confusion! yes, I meant `compounds`.

2020-07-31 21:25 UTC, dzleidig commented on Proposed/asc054.md
> +    "well_index": {
I think she means "<well_index>", e.g. "0".

2020-07-31 21:41 UTC, aota001 commented on Proposed/asc054.md
> +    "well_index": {
I guess this is how it is parsed/represented in the manifest. Technically the attribute is added to the Well. Updating.

2020-07-31 21:57 UTC, aota001 commented on Proposed/asc054.md
> +Any `compounds` data attached to the specified aliquot will be transferred over as an aliquot
Overall, there was a mix up in the usage of the word 'property'... :p i.e. object 'property' to explain attributes vs existing 'properties' attribute. My bad!

2020-07-31 22:30 UTC, EribertoLopez commented
Hey @aota001 I'm curious about this proposal. How different is a compound compared to a resource? Will this new default property be applied to all aliquots and Wells? We have the same issue with only being able to represent one resource even if multiple have been added to a well. It seem to me like the proposal should be generalized to properties in general and allow them to accept an array of data structures or strings.

2020-07-31 22:50 UTC, aota001 commented
@EribertoLopez Yes, this will be applied to all aliquots and wells. `compounds` is meant to accept a list of compounds that are linked or referenced to the container/aliquot object in the Web, and not just one. The long term plan here is to (eventually) make Compound class (hopefully with different subclasses/types to describe e.g. chemical, lysate, DNA, etc), and have `compounds` accept list of objects. I think we will eventually need more structured Compound class, and compound attribute (in aliquot) than to just include them in `properties` as any data structures. This proposal is just the first step based on what we can and need right now...

2020-08-03 20:56 UTC, joshhacksthings commented
> Yes, this will be applied to all aliquots and wells. 
This feels a bit sweeping to enforce all Well objects to have this property `.compounds`. 

> This proposal is just the first step based on what we can and need right now...
While I understand we're trying to make the new functionality in web accessible at the autoprotocol-python level, I do not think this is the way to do it. Other users of ApPY will not know what to do with these attributes that come with their `Well` objects. Not to mention, this isn't really the "first step" we're taking to change aliquots. We've added mass and other attributes that compounds require and making a heavily used data model a fragile Frankenstein.

I think this ASC requires further consideration, especially within the context of our currently existing data models. Some thoughts I have here:

1. If this only affects Strateos, can we dev on this internally first? ie, in `txappy`
2. Can we make a `Chemical` class that inherits from `Aliquot`? Then it can have top level properties like `id`, `molecularWeight`, `smile`, etc... without affecting attributes other protocol writers may have handrolled. This would be a great first step toward refactoring our data models which have been severely overloaded with properties like this (and previously `mass`) without a long term support plan in place.

Right now, I vote we (Strateos) have an internal discussion on what we can do to internally develop a new subclass of Aliquot.

2020-08-05 17:42 UTC, aota001 commented
@joshhacksthings Thanks for the feedback. Ya, I don't mind making this into private repo, as long as there is only one source for the all the compounds where the data is inherited from. In this case, since we don't have Chemical class, I was hoping to just get the data from Web and have it in Well (which is the same as Aliquot?) attributes for now. My thinking was that when we eventually make Chemical class, all the data is inherited from Well/Aliquot as you mentioned. 
Either way, I found out that having compounds molecular weight doesn't exactly solve the problem, and product requirement changed to include compound formula weight in the UI instead, so I am closing this PR for now. We should keep on rolling this conversation somewhere else, though, since we'll most likely need something like this anyways in the near future...

2020-08-05 17:42 UTC, closed without merging